### ISSUE TITLE
Test coverage for DialCollection code paths

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#277]
Some of the code paths for DialCollection are not covered by the current tests (mostly the binned spline paths).  This issue is to remind us (me!) that we need to make sure all of the (important) "dialSetDefinition" YAML options have a test.  The code paths being flagged for checks are are in DialCollection.cpp.

**Comment by nadrino** [comment]
Yeah, I think this comment apply also for event-by-event dials.

I mean, as GUNDAM was essentially tested to perform the OA fit we could create a test that accually does a very simplified fit (ie with a lot less events for instance) and check the results.

**Comment by ClarkMcGrew** [comment]
I'm chunking through the code paths.  So far, so good, but it might be worth thinking automating the test coverage checks.   So far I'm checking by hand using gcov (a *bit* painful) and output statements.  

GCov is the *right* tool, but it needs compiler support (with gcc `--coverage` and `-O0` are best) so it's less than optimal.  A "print statement kludge", or "hope for the best", are better solutions.

**Comment by ClarkMcGrew** [comment]
^^^ are _**PROBABLY**_ better solutions

**Comment by ClarkMcGrew** [comment]
This is being addressed in PR #298 but will probably NEVER be fully completed.  I suggest closing when #298 is merged.

**Comment by ClarkMcGrew** [comment]
Partially addressed with #298 merge.  We should open more specific coverage issues as needed.
