### ISSUE TITLE
EventDialCache thread safety

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#280]
`The` EventDialCache locks don't ensure thread-safety.  It should either be made thread-safe, or made to explicitly crash when it cannot maintain thread safety.

The EventDialCache is serving bare pointers to the indexed cache entries in `fetchNextCacheEntry()` which applies a lock so it can get a new index into the vector.  But, it can also allocate a new indexed cache entry and that might force the cache vector to be moved which will invalidate the pointers being used in any other thread accessing the cache.

The fetchNextCacheEntry allocation is mostly prevented by the preallocation of the cache in DataDispenser::preAllocateMemory.  The check should probably be changed into a trap against capacity and throw if the indexed cache vector needs to be resized.  An alternative would be to change to a collection that won't invalidate the pointer (e.g. forward_list).

**Comment by nadrino** [comment]
Yeah it's true. I've initially chosen the use of `std::vector` to keep memory as tight as possible for the propagation of weight. But this is probably irrelevant wrt the actual dial evaluation time consumption.

For the implementation of a `std::forward_list`, would it allow to split the loop per CPU like I'm using it in the reweight function? I mean this piece of code:

https://github.com/gundam-organization/gundam/blob/e249ff5d659b437933d946be638d5b435744fe2a/src/Propagator/src/Propagator.cpp#L852-L862

**Comment by nadrino** [comment]
I see, but `fetchNextCacheEntry` was only meant to be called during the initialization sequence. When the cache is used to reweight, this function shouldn't be called anymore

**Comment by ClarkMcGrew** [comment]
When I looked at it, I concluded `fetchNextCacheEntry` might be called from a thread, and it's got a lock.  

The cache is suppose to have been allocated before any the call to `fetchNextCacheEntry`, so my proposed solution is add a check against the vector capacity and throw an exception if the capacity is exceeded.  That will make an emplace or push safe.

**Comment by ClarkMcGrew** [comment]
This seems to be harmless ATM, so I'm kicking this to a later milestone (1.7.1).

**Comment by ClarkMcGrew** [comment]
Kicking this even further down the road!  This is a janitorial fix but the current code works.

**Comment by ClarkMcGrew** [comment]
I'm closing this.  A trap was added to catch an unsafe operation, and we'll get a throw.  That's probably the right think to do.  The code could be cleaned up a little bit (e.g. remove the lock), but that's not worth an "issue".
