### ISSUE TITLE
Towards dials that require event variables to evaluate

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#287]
Starting here a thread about implementing dials that need `PhysicsEvent` stored variable to evaluate.

As an example, the oscillation (survival) probability for SBL analysis:
$P(\nu_e \rightarrow \nu_e) = 1 - \sin^2(2\theta_{14})\sin^2\left(\Delta m^2_{41}L/4E\right)$.

Two fit parameters need to evaluate this formula $\theta_{14}$ and $\Delta m^2_{41}$, while $E$ is the neutrino energy which is different for each event.

`DialInputBuffer` seems to be the right candidate to handle the different inputs.

[TO BE CONTINUED]

**Comment by ClarkMcGrew** [comment]
If I'm reading correctly, this is a proposal to have a closure around some event information (e.g. the neutrino energy), not a proposal for multi-parameter dials (which DialInputBuffer already supports in principle).   If that's the case, the event information is a constant so it can be captured when a DialBase derived class is constructed.  It's completely analogous to how spline knots are captured by GeneralSpline (and friends).

**Comment by nadrino** [comment]
@ClarkMcGrew it is a good solution indeed! 
I also would like to think about the future additions such as having event vars that could move thanks to some dials. In that case we may need to capture the reference of the event var

**Comment by ClarkMcGrew** [comment]
Already being done with the tabulated dials, so I'm closing.
