### ISSUE TITLE
Syntax error, apparently in Logger.h

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#290]
Still need to look at the code, but here's the message 

/home/mcgrew/work/projects/gundam/submodules/simple-cpp-logger/include/Logger.h:219:38: error: in-class initialization of static data member 'std::unordered_set<void*> {anonymous}::Logger::_onceLogList_' of non-literal type

**Comment by ClarkMcGrew** [comment]
I'm looking at the overall code right now, and it seems like you might be testing with a permissive compiler.  I was just recompiling, so it's failing at the first error and there may be more problems I haven't seen yet.  However, after fixing the last bug, I see there are implicit `size_t` to `void*` conversions.  I suspect the _onceLogList_ declaration is wrong, but need to finish reading the code.

**Comment by nadrino** [comment]
https://github.com/gundam-organization/gundam/pulls

**Comment by nadrino** [comment]
Yeah it's actually a copy paste I've never updated for the non C++17 compilation modes

**Comment by ClarkMcGrew** [comment]
Fixed in #291
