### ISSUE TITLE
1.7.0 crash because of the configScan

### ISSUE THREAD

**Issue by LenaOsu** [gundam-organization/gundam#335]
When we add "llhStatPerSamplePerBin: true" and/or "weightPerSamplePerBin: true" in the configScan.yaml file, the 1.7.0 version crashes before doing the breakdown event.

**Comment by nadrino** [comment]
Solved in https://github.com/gundam-organization/gundam/commit/1731e6cdaa3caae381c0a6f355dca6111d1130c8 🙂
