### ISSUE TITLE
[Critical] Syntax errors in ConfigUtils.cpp

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#337]
Nothing more to add.  The code is probably assuming a standard and not checking what was used by ROOT.

**Comment by nadrino** [comment]
Is it already merged?? I just added this ConfigUtils.cpp a few minutes ago

**Comment by nadrino** [comment]
Do you have more details?

**Comment by ClarkMcGrew** [comment]
Just following up.  It is merged into main, but the problem seems to be in one of the sub-modules, and GUNDAM is depending on a very recent versions.  We really need a better update policy for the sub-modules since GUNDAM shouldn't be following that latest development.  Alternatively, the submodules should be explicitly part of our repository.

**Comment by ClarkMcGrew** [comment]
It looks like using `git submodule update` fixes the problem.  I think the issue is that there has to be versioning in any external that we are using, and we need to check the required version in GUNDAM `CMakeLists.txt`
