### ISSUE TITLE
Compilation issue for C++17

### ISSUE THREAD

**Issue by anfe29** [gundam-organization/gundam#358]
While compiling get this error:
/sps/t2k/amunoz/work/gundam/repo/gundam/src/Applications/src/gundamFitReader.cxx: In function 'int main(int, char**)':
/sps/t2k/amunoz/work/gundam/repo/gundam/src/Applications/src/gundamFitReader.cxx:122:6: error: call of overloaded 'readObject(std::__shared_ptr<TFile, __gnu_cxx::_S_atomic>::element_type*, <brace-enclosed initializer list>, main(int, char**)::<lambda(TNamed*)>)' is ambiguous
  122 |     });
      |      ^
In file included from /sps/t2k/amunoz/work/gundam/repo/gundam/src/Applications/src/gundamFitReader.cxx:8:
/sps/t2k/amunoz/work/gundam/repo/gundam/src/Utils/include/GundamUtils.h:72:45: note: candidate: 'static bool GundamUtils::ObjectReader::readObject(TDirectory*, const std::vector<std::basic_string<char> >&, const std::function<void(T*)>&) [with T = TNamed]'
   72 |     template<typename T> inline static bool readObject( TDirectory* f_, const std::vector<std::string>& objPathList_, const std::function<void(T*)>& action_ = [](T*){} ){
      |                                             ^~~~~~~~~~
/sps/t2k/amunoz/work/gundam/repo/gundam/src/Utils/include/GundamUtils.h:87:45: note: candidate: 'static bool GundamUtils::ObjectReader::readObject(TDirectory*, const string&, const std::function<void(T*)>&) [with T = TNamed; std::string = std::basic_string<char>]'
   87 |     template<typename T> inline static bool readObject( TDirectory* f_, const std::string& objPath_, const std::function<void(T*)>& action_ = [](T*){} ){ return readObject(f_, std::vector<std::string>{objPath_}, action_); }
      |                                             ^~~~~~~~~~
Whereas while compiling with C++14 there is no issue

**Comment by nadrino** [comment]
Solved in https://github.com/gundam-organization/gundam/pull/359
