### ISSUE TITLE
Add an option to analyze only a subset of events (e.g. the first 1000).

### ISSUE THREAD

**Issue by riccioc** [gundam-organization/gundam#367]
This feature can be very useful if we want to look at the interpolation of the cross-section or detector parameters.

**Comment by nadrino** [comment]
Hi Ciro! Thanks for creating the issue!

For the moment it is already possible to select a subset of event with `selectionCutFormula` and using ROOT tree tag `"Entry$ < 1000"`

But it's true it could be better supported by GUNDAM. Are you thinking about a cap of loaded events?

**Comment by riccioc** [comment]
Yes, I am thinking about an option for gundamFitter. Something like this: gundamFitter -c config.yaml  -n 1000 where -n 1000 means that it will load only the first 1000 events. Something more fancy could be that we select only CCQE or CC1pi events if we want to look at the dials affecting those.

**Comment by nadrino** [comment]
Added in https://github.com/gundam-organization/gundam/pull/416 !
