### ISSUE TITLE
Record parameter physical bounds seperately from allowed range

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#377]
Since parameters can be extended into non physical regions and still give mathematically (if not physically) correct results, we should keep track of the range where the parameter is defined separately from the range where it is physically meaningful.  For example a two neutrino disappearance can be fit with `(alpha*sin^2(1.27*L/E))` where `alpha` is interpreted as `sin^(2*theta)`.  The function is physical for `alpha` between zero and one, but defined for `-inf` to `inf`.

The physical range for a parameter should be saved separately from the range over which the parameter can be defined.  This will be useful when looking at the difference between frequentist and Bayesian results (i.e. comparing MINUIT and MCMC results).  It will also give us tools to speak about where the likelihood is defined as mathematical function versus where it is physically meaningful.

I propose adding new fitParameter fields analogous to  `parameterRange` and `parameterLimits` called `physicalRange` and `physicalLimits`.  The parameter range fields will be documented as the domain over which the model is defined, and the physical range fields will be documented as the domain over which the model is physically meaningful.

Note: The range over which the model is mirrored is a third range.  It's already separately defined by the dials and accessible through the FitParameter objects.

**Comment by riccioc** [comment]
I like this separation between the parameter ranges and limits and their physical ranges and limits. The name could reflect the definition more. For instance it can be `modelRange` and `modelLimit` instead of `parameterRange` or `parameterLimits`.

**Comment by ClarkMcGrew** [comment]
On a clean slate, I wouldn't disagree.  However, in the existing code, we are already using `parameterRange` and `parameterLimits`!   I don't think this warrants breaking the existing config files, or introducing synonyms, but YMMV.
