### ISSUE TITLE
Joint probability Barlow-Beeston divide by zero

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#390]
There is a (rare) special case in all of the OA2021 Barlow-Beeston joint probability calculations that results in a divide-by-zero.  It happens when the data and predicted values are exactly equal.  I've added a divide-by-zero check for now, but this needs a more careful look after the collaboration meeting

[I think this shows up in the MCMC because it calls the likelihood so many times for values well away from the minimum]

**Comment by nadrino** [comment]
IIRC, you added this 1e+20 instead of throwing because the MCMC needs to continue even if a MC bin has reach 0 right?
Could we throw an error that would only be caught within the MCMC instead of adding 1e+20?

**Comment by ClarkMcGrew** [comment]
I wouldn't throw because it's not an error.  Mathematically, the log likelihood needs to be defined for all input parameter values, but return "infinity" for parameter values that are not allowed.  The 1E+20 is suppose to represent `-log(0)` without causing any floating point exceptions (it could have been an infinity). 

I am very suspicious of the whole Barlow-Beeston implementation since it feels like there are some hidden numeric approximations (I didn't check it against the actual paper).  For instance, in this case, I recall that we are seeing at  ` z = x/y`, but I think that's an approximation for `z = f(x)/g(y)` when `f(x) ~ x` and `g(y) ~ y`, so the real value would be `z = lim(x->0, y->0) f(x)/g(y)`.

Another question is "why are we seeing zero probability parameter values, outside of the MCMC"?

**Comment by ClarkMcGrew** [comment]
I didn't use `infinity()` since I was afraid it would cause trouble with the gradient decent, but I'd be happy with that. 

Down the line, I'd like to take a little more time on the joint probability implementations.  There are a lot of edge cases in there that don't seem to exist in the original paper(s), particular when there are low MC statistics.

**Comment by nadrino** [comment]
@ClarkMcGrew Can we mark this as resolved now it's been merged to the main branch? :)

**Comment by ClarkMcGrew** [comment]
Umm... Has it been tested?  And, the commit I saw the other day was broken since it had a throw for infinity.  Did that get fixed?

**Comment by nadrino** [comment]
Yeah it was in the merge request you I commited the fix
