### ISSUE TITLE
MnSeedGenerator Negative G2 found

### ISSUE THREAD

**Issue by JiayuJi** [gundam-organization/gundam#401]
I am running the OA2021 data fit using the develop branch of Gundam. Gundam could not find the minimum and didn't run HESSE. The message printed out was:

12/09/2023 16:43:44 [FitterEngine] FitterEngine.cpp:458: Skipping post-fit error calculation since the minimizer did not converge.

and the error message was:

12/09/2023 16:19:43 [LikelInfo in <Minuit2>: MnSeedGenerator Negative G2 found - new state: 

If I run v1.7.2 the fit converge and HESSE is run but the error message just above (MnSeedGenerator Negative G2 found) is print anyway.

**Comment by nadrino** [comment]
Hi Jiayu,

Interesting, can you send me the command line and the output file (via Slack)?
