### ISSUE TITLE
Moving stat likelihood definition in a more appropriate place

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#422]
As GUNDAM is becoming more than a simple fitter, the Propagator engine has nothing to do with LLH-related.

LLH is used to quantify the distance between a model (MC) and the data. It would naturally sit within the Minimizer-like classes which use its value to find the best fit. This needs to be better defined since some apps like the CalcXsec needs it's value.

This little improvement might end up by re-organizing the code structure such that the objects are defined in their proper place with only the functionalities they are refering to.

**Comment by nadrino** [comment]
https://github.com/gundam-organization/gundam/pull/437

**Comment by riccioc** [comment]
Is this little improvement necessary? I am not sure I understand the goal of these changes and don't think we discussed this. I wouldn't start a refactoring of the code now that the activities of the group are intensifying. Then I was looking at the commit and it looks like some of them have removed useful comments that Clark wrote (eg in MinimizerBase.h?), changed names of classes and methods (for instance now MCMCInterface.h is SimpleMcmcInterface.h) that Clark has introduced, and moved files around. I wouldn't merge before a thoughtful review of the group.

**Comment by nadrino** [comment]
Hi Ciro,

> Is this little improvement necessary? I am not sure I understand the goal of these changes and don't think we discussed this.

This was a long term refactoring I've been wanted to perform since at least last year. At the begining moving the stat LLH function (JointProbability) was the only thing required but as the implementations did go, the LikelihoodInterface needed a refactoring too. These changes are necessary for me to have the suitable code structure in the future extensions of GUNDAM. I wanted to do this quickly on Friday but it ended up into refactoring a good part of the FitterEngine.

 > I wouldn't start a refactoring of the code now that the activities of the group are intensifying.

**It is just refactor so no new feature or breaking changes are expected with this branch. Even the original configuration format will work as expected.**

> Then I was looking at the commit and it looks like some of them have removed useful comments that Clark wrote (eg in MinimizerBase.h?), changed names of classes and methods (for instance now MCMCInterface.h is SimpleMcmcInterface.h) that Clark has introduced, and moved files around. I wouldn't merge before a thoughtful review of the group.

We can discuss this more within the group, but the idea is to have a collection of classes that have relevant names. In fact this reminds me that I need to write some code guidelines. For the MCMC interface, there's almost no changes. The only modifications are the access of some external class members that have been relocated. Also about the comments, I may have a different few on the use of them. Those files, and expetially the MinimizerBase class, have a bunch of comments in the header which obfuscate the components of the class.

In general for coding in C++, I like to say that comments are most of the time non necessary. It's always better to have a file structure that explicitly show the intention of the dev with the right naming of variables. Comments should only be used in non-trivial parts of the code, which should not concern the file header (that should stay as simple as possible). Typically in classes definition the class name has to tell what is the functionality of it. Then we use default C-tor/D-tor, a buch of setters/getters and some "core" methods. Those core methods might be non-trivial but the class name should suggest what's going inside the hood. If it appear that even tho it is non trivial, it usually indicates that the class structure should be revised in order to have the proper collection of building blocks to the overall code.
