### ISSUE TITLE
GUNDAM 1.8.0: LLH scans aborted

### ISSUE THREAD

**Issue by riccioc** [gundam-organization/gundam#485]
LLH scans aborted with this message: 

`terminate called after throwing an instance of 'std::runtime_error'
  what():  exception thrown by the logger: std::isnan(llh) or std::isinf(llh)`

The command used is 

`gundamFitter -d --scan -c configOA2024.yaml -t 32 -of override/noEigen.yaml`

I have added the override to disable the eigen-decomposition to test it was not causing the issue. 

I think this was solved in 1.9.0 or in the main but we should have this fixed in version 1.8.X since we decided that this should be the LTS version. I didn't check but this may affect also the sigma variations.

**Comment by ClarkMcGrew** [comment]
I'll tackle this.  The branch will be LTS/issue485/LLHNotANumber.  It's hard to create a simple test to demonstrate the bug, but the main issue is that "inf" is a valid likelihood, so it should be accepted.  In any case, that should not cause the program to crash.
