### ISSUE TITLE
 LTS/1.8.x: Option isFixed doesn't work

### ISSUE THREAD

**Issue by riccioc** [gundam-organization/gundam#505]
Option isFixed in configuration files doesn't work. Previously a parameter was just disabled, ie the option isEnabled was false, when a parameter was fixed.

**Comment by ClarkMcGrew** [comment]
As per discussion with @nadrino : Parameter fixing is available as part of the Parameter class, but the configuration option has only been added in main.  Based on discussions, the ability to set the option should be added to the 1.8.x YAML configuration handling.
