### ISSUE TITLE
LTS/1.8.x: Segmentation violation using --gpu option

### ISSUE THREAD

**Issue by riccioc** [gundam-organization/gundam#507]
I have tested --gpu option and GUNDAM crashed.

12/05/2024 22:24:06 [Cache::Manager]: Build the internal caches 
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD1 #nu_{#mu} CC 0#pi 0p 0#gamma Fwd with 254 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD1 #nu_{#mu} CC 0#pi Np 0#gamma Fwd with 226 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD1 numuCC 0#pi 0#gamma No Protons Bwd with 32 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD1 numuCC 0#pi Bwd 0#gamma N Protons Bwd with 62 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD1 numuCC 0#pi 0#gamma No Protons HA with 98 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD1 numuCC 0#pi 0#gamma N Protons HA with 104 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD1 #nu_{#mu} CC 1#pi 0#gamma Fwd with 142 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD1 numuCC 1Pi 0#gamma HAFwd with 32 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD1 #nu_{#mu} CC Other 0#gamma with 146 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD1 #nu_{#mu} CC #gamma with 184 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD2 #nu_{#mu} CC 0#pi 0p 0#gamma Fwd with 254 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD2 #nu_{#mu} CC 0#pi Np 0#gamma Fwd with 170 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD2 numuCC 0#pi 0#gamma No Protons Bwd with 20 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD2 numuCC 0#pi 0#gamma N Protons Bwd with 56 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD2 numuCC 0#pi HA 0#gamma No Protons with 102 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD2 numuCC 0#pi 0#gamma N Protons HA with 80 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD2 #nu_{#mu} CC 1#pi 0#gamma Fwd with 162 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FGD2 numuCC 1Pi 0#gamma HAFwd with 32 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD2 #nu_{#mu} CC Other 0#gamma with 154 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for FHC FGD2 #nu_{#mu} CC #gamma with 155 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD1 Anti #nu_{#mu} CC 0#pi with 242 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD1 Anti #nu_{#mu} CC 1#pi with 112 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD1 Anti #nu_{#mu} CC Other with 112 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 Anti #nu_{#mu} CC 0#pi with 244 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 Anti #nu_{#mu} CC 1#pi with 90 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 Anti #nu_{#mu} CC Other with 90 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD1 #nu_{#mu} (background) CC 0#pi in AntiNu_Mode with 212 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD1 #nu_{#mu} (background) CC 1#pi in AntiNu_Mode with 128 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::
 *** Break *** segmentation violation
Manager]: Add histogram for RHC FGD1 #nu_{#mu} (background) CC Other in AntiNu_Mode with 128 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 #nu_{#mu} (background) CC 0#pi in AntiNu_Mode with 184 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 #nu_{#mu} (background) CC 1#pi  in AntiNu_Mode with 90 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Add histogram for RHC FGD2 #nu_{#mu} (background) CC Other  in AntiNu_Mode with 107 cells (includes under/over-flows)
12/05/2024 22:24:49 [Cache::Manager]: Cache for 2394990 events -- using 782 parameters
12/05/2024 22:24:49 [Cache::Manager]:     Compact splines: 0 (0 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Monotonic splines: 2275881 (0.950267 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Uniform Splines: 20875126 (8.71616 per event)
12/05/2024 22:24:49 [Cache::Manager]:     General Splines: 1910077 (0.79753 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Graphs: 6078823 (2.53814 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Normalizations: 6289132 (2.62595 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Shifts: 723 (0.00030188 per event)
12/05/2024 22:24:49 [Cache::Manager]:     Histogram bins: 4204 (569.693 events per bin)
12/05/2024 22:24:49 [Cache::Manager]:     Monotonic spline cache uses 19790521 control points -- (8.69576 points per spline) for 2275881 splines
12/05/2024 22:24:49 [Cache::Manager]:     Uniform spline cache uses 276335684 control points -- (13.2376 points per spline) for 20875126 splines
12/05/2024 22:24:49 [Cache::Manager]:     General spline cache uses 40769477 control points -- (21.3444 points per spline) for 1910077 splines
12/05/2024 22:24:49 [Cache::Manager]:     Graph cache uses 39796282 control points -- (6.54671 points per graph)
12/05/2024 22:24:49 [Cache::Manager]: Creating the Cache::Manager
12/05/2024 22:24:49 [Cache::Manager]: Creating cache manager
12/05/2024 22:24:49 [Cache::Parameters]: Cached Parameters -- input parameter count: 782
12/05/2024 22:24:49 [Cache::Weights]: Cached Weights -- output results reserved: 2394990
12/05/2024 22:24:49 [Cache::Weights]: Cached Weights -- approximate memory size: 0.0383198 GB
12/05/2024 22:24:49 [Cache::Weight::Normalization]: Cached Weights: reserved Normalizations: 6289132
12/05/2024 22:24:49 [Cache::Weight::Normalization]: Approximate Memory Size: 0.0377348 GB
12/05/2024 22:24:49 [Cache::Weight::CompactSpline]: Reserved compactSpline Splines: 0
12/05/2024 22:24:49 [Cache::Weight::MonotonicSpline]: Reserved compactSpline Splines: 2275881
12/05/2024 22:24:49 [Cache::Weight::MonotonicSpline]: Reserved compactSpline Spline Knots: 19790521
12/05/2024 22:24:49 [Cache::Weight::MonotonicSpline]: Approximate Memory Size for compactSpline: 0.181083 GB
12/05/2024 22:24:49 [Cache::Weight::UniformSpline]: Reserved uniformSpline Splines: 20875126
12/05/2024 22:24:49 [Cache::Weight::UniformSpline]: Reserved uniformSpline Spline Knots: 276335684
12/05/2024 22:24:49 [Cache::Weight::UniformSpline]: Approximate Memory Size for uniformSpline: 2.41944 GB
12/05/2024 22:24:49 [Cache::Weight::GeneralSpline]: Reserved generalSpline Splines: 1910077
12/05/2024 22:24:49 [Cache::Weight::GeneralSpline]: Reserved generalSpline Spline Knots: 40769477
12/05/2024 22:24:49 [Cache::Weight::GeneralSpline]: Approximate Memory Size for generalSpline: 0.345257 GB
12/05/2024 22:24:49 [Cache::Weight::Graph]: Reserved graph Graphs: 6078823
12/05/2024 22:24:49 [Cache::Weight::Graph]: Reserved graph Graph Data: 39796282
12/05/2024 22:24:49 [Cache::Weight::Graph]: Approximate Memory Size for graph: 0.379158 GB
12/05/2024 22:24:49 [Cache::IndexedSums]: Cached IndexedSums -- bins reserved: 4204
12/05/2024 22:24:49 [Cache::IndexedSums]: Cached IndexedSums -- approximate memory size: 4.82361 MB

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007ffbb1495787 in __GI___wait4 (pid=3178602, stat_loc=stat_loc
entry=0x7ffc8970c228, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007ffbb1495707 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffc8970c228, options=options
entry=0) at waitpid.c:38
#2  0x00007ffbb1413ae7 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007ffbb27360bc in TUnixSystem::StackTrace() () from /home/riccioc/root/6.24.06/root_install/lib/libCore.so
#4  0x00007ffbb27336b5 in TUnixSystem::DispatchSignals(ESignals) () from /home/riccioc/root/6.24.06/root_install/lib/libCore.so
#5  <signal handler called>
#6  __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:204
#7  0x00007ffbb1a71f3e in Cache::IndexedSums::IndexedSums(hemi::Array<double>&, unsigned long) () from /home/riccioc/gundam/v1.8.x-gpu/build/Linux/lib/libGundamCache.so
#8  0x00007ffbb19f982e in std::make_unique<Cache::IndexedSums, hemi::Array<double>&, int&> () at /usr/include/c++/10/bits/unique_ptr.h:961
#9  Cache::Manager::Manager (this=0x562372a849c0, events=<optimized out>, parameters=<optimized out>, norms=<optimized out>, compactSplines=<optimized out>, compactPoints=0, monotonicSplines=2275881, monotonicPoints=19790521, uniformSplines=20875126, uniformPoints=276335684, generalSplines=1910077, generalPoints=40769477, graphs=6078823, graphPoints=39796282, histBins=4204, spaceOption="space") at /home/riccioc/gundam/v1.8.x-gpu/src/CacheManager/src/CacheManager.cpp:113
#10 0x00007ffbb19fb1a5 in Cache::Manager::Build (sampleList=..., eventDials=...) at /home/riccioc/gundam/v1.8.x-gpu/src/CacheManager/src/CacheManager.cpp:309
#11 0x00007ffbb1c458c6 in Propagator::initializeImpl (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/src/Propagator/include/Propagator.h:57
#12 0x00005620cf2e070c in GenericToolbox::InitBaseClass::initialize (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.InitBaseClass.Impl.h:18
#13 GenericToolbox::ConfigBaseClass<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::initialize (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.ConfigBaseClass.Impl.h:34
#14 0x00007ffbb1ce9350 in FitterEngine::initializeImpl (this=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/src/Fitter/src/FitterEngine.cpp:93
#15 0x00005620cf2e070c in GenericToolbox::InitBaseClass::initialize (this=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.InitBaseClass.Impl.h:18
#16 GenericToolbox::ConfigBaseClass<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::initialize (this=this
entry=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.ConfigBaseClass.Impl.h:34
#17 0x00005620cf2d9e21 in main (argc=<optimized out>, argv=<optimized out>) at /home/riccioc/gundam/v1.8.x-gpu/src/Applications/src/gundamFitter.cxx:324
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:204
#7  0x00007ffbb1a71f3e in Cache::IndexedSums::IndexedSums(hemi::Array<double>&, unsigned long) () from /home/riccioc/gundam/v1.8.x-gpu/build/Linux/lib/libGundamCache.so
#8  0x00007ffbb19f982e in std::make_unique<Cache::IndexedSums, hemi::Array<double>&, int&> () at /usr/include/c++/10/bits/unique_ptr.h:961
#9  Cache::Manager::Manager (this=0x562372a849c0, events=<optimized out>, parameters=<optimized out>, norms=<optimized out>, compactSplines=<optimized out>, compactPoints=0, monotonicSplines=2275881, monotonicPoints=19790521, uniformSplines=20875126, uniformPoints=276335684, generalSplines=1910077, generalPoints=40769477, graphs=6078823, graphPoints=39796282, histBins=4204, spaceOption="space") at /home/riccioc/gundam/v1.8.x-gpu/src/CacheManager/src/CacheManager.cpp:113
#10 0x00007ffbb19fb1a5 in Cache::Manager::Build (sampleList=..., eventDials=...) at /home/riccioc/gundam/v1.8.x-gpu/src/CacheManager/src/CacheManager.cpp:309
#11 0x00007ffbb1c458c6 in Propagator::initializeImpl (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/src/Propagator/include/Propagator.h:57
#12 0x00005620cf2e070c in GenericToolbox::InitBaseClass::initialize (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.InitBaseClass.Impl.h:18
#13 GenericToolbox::ConfigBaseClass<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::initialize (this=0x7ffc8970fd40) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.ConfigBaseClass.Impl.h:34
#14 0x00007ffbb1ce9350 in FitterEngine::initializeImpl (this=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/src/Fitter/src/FitterEngine.cpp:93
#15 0x00005620cf2e070c in GenericToolbox::InitBaseClass::initialize (this=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.InitBaseClass.Impl.h:18
#16 GenericToolbox::ConfigBaseClass<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::initialize (this=this
entry=0x7ffc8970fcd0) at /home/riccioc/gundam/v1.8.x-gpu/submodules/cpp-generic-toolbox/include/implementation/GenericToolbox.ConfigBaseClass.Impl.h:34
#17 0x00005620cf2d9e21 in main (argc=<optimized out>, argv=<optimized out>) at /home/riccioc/gundam/v1.8.x-gpu/src/Applications/src/gundamFitter.cxx:324
===========================================================

**Comment by ClarkMcGrew** [comment]
The stack dump seems to indicate a allocation error in CacheIndexedSums (that probably means the job doesn't have enough memory allocated).  There is a try-catch around the allocation, but it might be getting an unanticipated exception type.

**Comment by ClarkMcGrew** [comment]
This runs when there is sufficient memory. The crash was caused by an out-of-memory error on the host (either, the memory was to fragmented to allocate a large continuous block, or there wasn't enough memory allocated).  There are traps with error messages, but the Logger is  dumping LogError messages into /dev/null when there are fatal exceptions.
