### ISSUE TITLE
NaN value issue on LTS/1.8.x 

### ISSUE THREAD

**Issue by LenaOsu** [gundam-organization/gundam#540]
When using external mirroring for cross-section splines (eigen decomposition for Flux,xsec FSI and ND cov. matrix, NO scan option), and already commented L214 (all the paragraph) in JointProbability.cpp and L91 in Parameter.cpp (because they lead to NaN issues too), it still remains an error that makes crash the Data fit : 
LogThrowIf( std::isnan(parameterValue), "Attempting to set NaN value for par:" << std::endl << this->getSummary()
The " this->getSummary() " does not print anything, it crashes before. This happens during MIGRAD process, cannot reach Hesse.

**Comment by ClarkMcGrew** [comment]
Did I understand correctly that you needed to comment out Parameter.cpp L91 to stop a crash.  That would mean that Parameter::setParameter is being called with a NAN, which is a straight out bug.

Similarly, JointProbability.cpp L214 should probably be proceeded by a LogThrowIf(std::isnan(chiSq)) since that should never occur for correct inputs.  An infinite chisq can be valid, but during a minuit fit tends to indicate there is a problem with the inputs.

Both of those make it sound like there is a problem with the inputs.  Have you found anything new?

**Comment by LenaOsu** [comment]
Hi Clark,

Yes, you understood well ! It seems that the only parameters that changes a lot using the GUNDAM internal mirroring or the mirroring made from OAGenWeightsApps is R_S_Delta_Decay. I'll run a fit without enabling it and see if it crashes or not. I did not get this issue when I used the GUNDAM internal mirroring, I will also check splines by event in the new data inputs files. But yes, event if I mute L214 in JointProbability.cpp and L91 in Parameter.cpp i still get a NaN value error that make crash the fit before to reach Hesse..
Thanks a lot Clark,
I will try to clarify the potential input issue,
Léna

________________________________
De : Clark McGrew ***@***.***>
Envoyé : vendredi 28 juin 2024 05:22
À : gundam-organization/gundam ***@***.***>
Cc : LenaOsu ***@***.***>; Author ***@***.***>
Objet : Re: [gundam-organization/gundam] NaN value issue on LTS/1.8.x (Issue #540)


Did I understand correctly that you needed to comment out Parameter.cpp L91 to stop a crash. That would mean that Parameter::setParameter is being called with a NAN, which is a straight out bug.

Similarly, JointProbability.cpp L214 should probably be proceeded by a LogThrowIf(std::isnan(chiSq)) since that should never occur for correct inputs. An infinite chisq can be valid, but during a minuit fit tends to indicate there is a problem with the inputs.

Both of those make it sound like there is a problem with the inputs. Have you found anything new?

**Comment by LenaOsu** [comment]
I mean, MC inputs files*
Léna
________________________________
De : Léna Osu ***@***.***>
Envoyé : vendredi 28 juin 2024 11:50
À : gundam-organization/gundam ***@***.***>
Objet : RE: [gundam-organization/gundam] NaN value issue on LTS/1.8.x (Issue #540)

Hi Clark,

Yes, you understood well ! It seems that the only parameters that changes a lot using the GUNDAM internal mirroring or the mirroring made from OAGenWeightsApps is R_S_Delta_Decay. I'll run a fit without enabling it and see if it crashes or not. I did not get this issue when I used the GUNDAM internal mirroring, I will also check splines by event in the new data inputs files. But yes, event if I mute L214 in JointProbability.cpp and L91 in Parameter.cpp i still get a NaN value error that make crash the fit before to reach Hesse..
Thanks a lot Clark,
I will try to clarify the potential input issue,
Léna

________________________________
De : Clark McGrew ***@***.***>
Envoyé : vendredi 28 juin 2024 05:22
À : gundam-organization/gundam ***@***.***>
Cc : LenaOsu ***@***.***>; Author ***@***.***>
Objet : Re: [gundam-organization/gundam] NaN value issue on LTS/1.8.x (Issue #540)


Did I understand correctly that you needed to comment out Parameter.cpp L91 to stop a crash. That would mean that Parameter::setParameter is being called with a NAN, which is a straight out bug.

Similarly, JointProbability.cpp L214 should probably be proceeded by a LogThrowIf(std::isnan(chiSq)) since that should never occur for correct inputs. An infinite chisq can be valid, but during a minuit fit tends to indicate there is a problem with the inputs.

Both of those make it sound like there is a problem with the inputs. Have you found anything new?

**Comment by ClarkMcGrew** [comment]
Closed by #543
