### ISSUE TITLE
CMake won't check for HEMI library when the CacheManager is enabled for the compilation

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#541]
As `WITH_CACHE_MANAGER=ON` by default, the HEMI headers are expected during the compilation but CMake won't check for it.

HEMI was not intended to be a required dependency of GUNDAM, so I would suggest either to disable the CacheManager by default in the CMake configuration, or make sure it can compile without HEMI

@ClarkMcGrew what is your opinion on this?

**Comment by ClarkMcGrew** [comment]
I'm not sure what your saying.  Those headers are part of the CacheManager source, not a separate dependency.
