### ISSUE TITLE
Allow MINUIT to set invalid parameters to help debug invalid likelihoods

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#605]
We are seeing strange corner cases where MINUIT is calling evalFit with NaN parameter values.  It's rare, so jobs could continue with extra debugging information.  

The suspicion is that the NaN values result from MINUIT getting an Inf likelihood, and that might result from a bounded eigen decomposed parameter going outside of physical bounds.  This should push the error a bit lower in the code and help with understanding.  MINUIT may also be able to recover.

**Comment by nadrino** [comment]
The important thing to do here is to make sure the fitter engine returns a NaN for the llh value if any of the parameter is set to NaN.

We could keep the checks you've implemented before which prevent the user to set NaN parameter values, but let MINUIT set those parameters with another routine, like `Parameter::forceSetParameterValue();`.

This way the check for invalid NaN wouldn't be performed at all while running MINUIT

**Comment by ClarkMcGrew** [comment]
Added as part of other work.  No longer an issue.
