### ISSUE TITLE
Issue in gundamCalcXsec when generating xsec sample plots

### ISSUE THREAD

**Issue by XingyuZhao1995** [gundam-organization/gundam#651]
I noticed an issue when running gundamCalcXsec. This happened in the generating xsec sample plots step, mainly this part
```
    const CrossSectionData* xsecDataPtr{nullptr};
    for( auto& xsecData : crossSectionDataList ){
      if( xsecData.samplePtr  == histHolder.samplePtr){
        xsecDataPtr = &xsecData;
        break;
      }  
    }
    LogThrowIf(xsecDataPtr==nullptr, "corresponding data not found");
```
It seems that this pointer matching is not successful so that the message showed to me:
```
2024.10.04 17:49:59 ERROR gundamCalcXsec: (int main(int, char**)): corresponding data not found
terminate called after throwing an instance of 'std::runtime_error'
  what():  exception thrown by the logger:xsecDataPtr==nullptr: "corresponding data not found"
```
I tried to look a bit but didn't found what was the reason. However a temporary solution could be replacing the pointer check with name check
```
      if( (xsecData.samplePtr)->getName()  == (histHolder.samplePtr)->getName()){
        xsecDataPtr = &xsecData;
        break;
      }  
```
so that I can run gundamCalcXsec to the end and get valid results.

I created a branch `feature/check_calcxsec` for this update, but guess this is not the best solution. Could you help to check where the issue comes from? Thanks!

**Comment by nadrino** [comment]
Good catch indeed! Thank you very much @XingyuZhao1995! The sample pointer matching where were working as the Propagator got inherited from the the FitterEngine. However it's not the case anymore. 

Your workaround should perfectly fit! I'll have a look to your branch

**Comment by XingyuZhao1995** [comment]
Hi @nadrino do we have any update about this issue?

**Comment by nadrino** [comment]
You did a PR already, right?

**Comment by nadrino** [comment]
It's been merged already: https://github.com/gundam-organization/gundam/pull/652

It's on the main branch then!
