### ISSUE TITLE
linear interpolation changes between 1.8.2 and 1.8.3 gundam version

### ISSUE THREAD

**Issue by LenaOsu** [gundam-organization/gundam#673]
No more symmetry using linear interpolation passing to 1.8.3 gundam version, here is a png of the working session (hope it will help!)
![comparison_gundam_versions](https://github.com/user-attachments/assets/03ac0b7e-f0a8-4b62-909e-74c778cab7fd)

**Comment by ClarkMcGrew** [comment]
Good catch.  I forgot to save the "unfixed" version of the plot, but it was wrong.  The 1.8.3 code worked for two knots (the most common case), but had a bug for more than two.  Here's the fixed graph (knots at [-1,1], [0,0], and [1,1]).  The wiggle at "0" is a root artifact.

![100CheckGraph2](https://github.com/user-attachments/assets/13478793-0d82-47a1-a6f6-3d056f1e692b)

**Comment by LenaOsu** [comment]
Thanks a lot Clark ! Will update now
