### ISSUE TITLE
DialInputBuffer error message misformated with incorrect user input

### ISSUE THREAD

**Issue by ClarkMcGrew** [gundam-organization/gundam#674]
The error message printed by DialInputBuffer when it gets an invalid parameter is being generated directly by LogThrowIf and is not formatted, and is affected by the LogThrow flush bug.  This trap is usually triggered by a problem with the USER inputs, so throw isn't ideal.  A useful fix would be to change this from a throw to an exit(with failure) and make sure that a useful error message is printed.

**Comment by nadrino** [comment]
Could we add a `LogExitIf` to handle these specific cases?
