### ISSUE TITLE
LightGraph extrapolation from the positive side

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#702]
While monitoring some parameter scans for the cross-section analysis "CC0$\pi$+CC1$\pi$ 4$\pi$", we've found some strange extrapolation of simple graphs (cf. attached image).

I found a similar problem while running p-values with some toys: some LightGraph would return a NaN response when extrapolating to the positive side.

The issue actually comes from `CalculateGraph` while looking for the appropriate knot index. For a given x value, a binary search is performed to find the index of the first graph point in which x is greater. For a "normal" case, the graph would find the points `x1` and `x2` for which: `x1 < x < x2`. However, when the binary search finds the last point of the graph (which will be labeled as x1), `x2` does not exist so the function is seaking for an out of bound value!

For positive extrapolation, one have to make sure the binary search never return `x1` as the last point of the graph.

I'll make a PR to propose a fix for this issue.

![screenshot_2024-11-18_at_15 28 25](https://github.com/user-attachments/assets/cb0b15d3-3af4-4cc3-b6f5-8c39dd5922a6)

**Comment by nadrino** [comment]
Solved on https://github.com/gundam-organization/gundam/pull/703

**Comment by ClarkMcGrew** [comment]
This is not the fix you are looking for, and the "fix" seems to be hiding some other bug someplace.

**Comment by nadrino** [comment]
Let's reopen the issue then!

**Comment by ClarkMcGrew** [comment]
The latest merge makes it so CalculateGraph will be very noisy (on a CPU) if it is getting funky inputs.  Chances are this is a problem in config files, inputs, or parameters not being properly set.
